import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import {Sidebar} from '@/components/Sidebar'
import {Header} from '@/components/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Admin Dashboard',
  description: 'Generated by Kohei Nagamatsu',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <div className={"w-full bg-black text-white p-6"}>
          <div className={"flex space-x-4 border rounded-xl"}>
            <Sidebar adminName={"Kohei Dashboard"} logoImage={"/images/logo.webp"} profileImage={"/images/my-profile.webp"} name={"Kohei"} info={"developper"} />
            <div className={"w-[75%] space-y-4"}>
              <Header />
              <div className={"h-[85%] border border-[#B3B3B3] hidden-scrollbar overflow-y-scroll rounded-xl my-5 mr-3 "}>
                {children}
              </div>
            </div>
          </div>

        </div>

      </body>
    </html>
  )
}
